# numbers = [1,2,3,4,5]
# numbers[1:4] = [] # this is equivelent to del numbers[1:4] because it removes numbers 2 (counted from 0 that is) through to 4
# print(numbers)
tutorial_complete = 0
# ------------List Methods------------
# tutorial_check = input("") Adding after typing this document#

side_panel = "# "
character = "#"
top = "which section of the tutorial do you want to skip to? (use numbers only)"
top_and_bottom_length = len(top) + 3

while tutorial_complete == int(0):
    print("#" * top_and_bottom_length)
    print(side_panel + "which section of the tutorial do you want to skip to? (use numbers only)" + "#")
    print("#" * top_and_bottom_length)
    print(side_panel + "01 - Introduction" + "                                                       #")
    print(side_panel + "02 - APPEND" + "                                                             #")
    print(side_panel + "03 - CLEAR" + "                                                              #")
    print(side_panel + "04 - COPY" + "                                                               #")
    print(side_panel + "05 - COUNT" + "                                                              #")
    print(side_panel + "06 - EXTEND (being worked on)" + "                                           #")
    print(side_panel + "07 - INDEX" + "                                                              #")
    print(side_panel + "08 - INSERT" + "                                                             #")
    print(side_panel + "09 - POP" + "                                                                #")
    print(side_panel + "type 00 to see this index again at any point of the tutorial" + "            #")
    print("#" * top_and_bottom_length)
    tutorial_section = int(input("Choose number, type 99 to quit or 00 to see index: "))


    if tutorial_section == int(00):
        print("#" * top_and_bottom_length)
        print(side_panel + "which section of the tutorial do you want to skip to? (use numbers only)" + "#")
        print("#" * top_and_bottom_length)
        print(side_panel + "01 - Introduction" + "                                                       #")
        print(side_panel + "02 - APPEND" + "                                                             #")
        print(side_panel + "03 - CLEAR" + "                                                              #")
        print(side_panel + "04 - COPY" + "                                                               #")
        print(side_panel + "05 - COUNT" + "                                                              #")
        print(side_panel + "06 - EXTEND (being worked on)" + "                                           #")
        print(side_panel + "07 - INDEX" + "                                                              #")
        print(side_panel + "08 - INSERT" + "                                                             #")
        print(side_panel + "09 - POP" + "                                                                #")
        print(side_panel + "type 00 to see this index again at any point of the tutorial" + "            #")
        print("#" * top_and_bottom_length)
        tutorial_section = int(input("Choose number, type 99 to quit or 00 to see index: "))

    if tutorial_section == int(1):
        print()
        print()
        print()
        print()
        print(" 01 - Introduction")
        print()
        print("A method is a function that is tightly coupled to some object, be it a list, number, a string, or whatever. in general a method is called like this:")
        print("object.method(arguments)")
        print()
        print("A method call looks just like a function call, except that the object is put before the method name, with a dot seperating them.")
        print("Lists have several methods that allow you to examine or modify their contents.")
        print()
        print("###-END OF INTRODUCTION-###")
        tutorial_section = int(input("Choose number, type 99 to quit or 00 to see index: "))

    if tutorial_section == int(2):
        print()
        print()
        print()
        print()
        print(" 02 - APPEND")
        print()
        print("The append method is used to append an object to the end of a list")
        print("1st = [1,2,3]")
        print("lst.append(4)")
        print("print(lst)")
        print()
        print("----program section------")
        lst = [1,2,3]
        lst.append(4)
        print(lst)
        print("---end program---")
        print()
        print("It's also important to note that append, like several other methods, changes the list in place. this means that it does not simply return")
        print("a new, modified list; instead, it modifies the old one directly. This is usually what you want, but it may sometimes cause trouble")
        print()
        print("###-END OF APPEND-###")
        tutorial_section = int(input("Choose number, type 99 to quit or 00 to see index: "))

    if tutorial_section == int(3):
        print()
        print()
        print()
        print()
        print("03 - CLEAR")
        print()
        print("The clear method clears the contents of a list in place")
        print("lst = [1,2,3]")
        print("lst.clear()")
        print("print(lst)")
        print("[]")
        print()
        print("----Program section------")
        lst = [1,2,3]
        lst.clear()
        print(lst)
        print("---end program---")
        print()
        print("It's similar to the slice assignment lst[:] = []")
        print()
        print("###-END OF CLEAR-###")
        tutorial_section = int(input("Choose number, type 99 to quit or 00 to see index: "))



    if tutorial_section == int(4):
        print()
        print()
        print()
        print()
        print("04 - COPY")
        print()
        print("The copy method copies a list. Recall that a normal assignment simply binds another to the same list")
        print("a = [1,2,3]")
        print("b = a")
        print("b[1] = 4")
        print("print(a)")
        print("[1,4,3]")
        print()
        print("----Program section A----")
        a = [1,2,3]
        b = a
        b[1] = 4
        print(a)
        print("---end program---")
        print()
        print("If you want a and b to be seperate lists, you have to bind b to a copy of a")
        print()
        print("a = [1,2,3]")
        print("b = a.copy()")
        print("b[1] = 4")
        print("print(a)")
        print()
        print("----program section B----")
        a = [1,2,3]
        b = a.copy()
        b[1] = 4
        print(a)
        print("---end program")
        print()
        print("###-END OF COPY-###")
        tutorial_section = int(input("Choose number, type 99 to quit or 00 to see index: "))




    if tutorial_section == int(5):
        print()
        print()
        print()
        print()
        print("05 - COUNT")
        print()
        print("The count method counts the occurances of an element in a list")
        print("lst = ['to' 'be' 'or' 'not' 'to' 'be']")
        print("lst2 = lst.count("'to'")")
        print("print(lst2)")
        print()
        print("----Program section------")
        lst = ['to', 'be', 'or', 'not', 'to', 'be']
        lst2 = lst.count('to')
        print(lst2)
        print("---end program---")
        print()
        print()
        print("x = [[1,2],1,1,[2,1,[1,2]]]")
        print("x2 = x.count(1)")
        print("print(x2)")
        print("2")
        print()
        print("----Program Section------")
        x = [[1,2],1,1,[2,1,[1,2]]]
        x2 = x.count(1)
        print(x2)
        print("---end program---")
        print()
        print("###-END OF COUNT-###")
        tutorial_section = int(input("Choose number, type 99 to quit or 00 to see index: "))




    if tutorial_section == int(6):
        print()
        print()
        print()
        print()
        print("06 - EXTEND")
        print()
        print("The extend method allows you to append several values at once by supplying a sequence of the values you want to append.")
        print("In other words, your original list has been extended by the other one")
        print("a = [1,2,3]")
        print("b = [4,5,6]")
        print("a.extend(b)")
        print("print(a)")
        print("[1,2,3,4,5,6]")
        print()
        print("----Program Section------")
        a = [1,2,3]
        b = [4,5,6]
        a.extend(b)
        print(a)
        print("---end program---")
        print()
        print("This may seem similar to concatenation, but the important difference is that the extended sequence (in this case, a) is modified. This is")
        print("not the case in ordinary concatenation, in which a completely new sequence is returned.")
        print("a = [1,2,3]")
        print("b = [4,5,6]")
        print("number = (a + b)")
        print("print (number)")
        print("[1,2,3,4,5,6]")
        print("print(a)")
        print("[1,2,3]")
        print()
        print("----Program Section------")
        a = [1,2,3]
        b = [4,5,6]
        number = a + b
        print(number)
        print(a)
        print("---end program---")
        print()
        print("As you can see, the concatenated list looks exactly the same as the extended one in the previous example, yet a hasn't changed this time.")
        print("Because ordinary concatenation must make a new list that contains copies of a and b, it isn't quite as efficient as using extend if what you want")
        print("is something like this")
        print("a = a + b")
        print()
        print("Also, this isn't an in-place operation--it won't modify the original. The effect of extend can be achieved by assigning to slices, as follows:")
        print("a = [1,2,3]")
        print("b = [4,5,6]")
        print("a[len(a):] = b")
        print("print(a)")
        print("[1,2,3,4,5,6]")
        print()
        print("----Program Section------")
        a = [1,2,3]
        b = [4,5,6]
        a[len(a):] = b
        print(a)
        print("---end program---")
        print()
        print("While this works, it isn't quite as readable")
        print()
        print("###-END OF EXTEND-###")

        tutorial_section = int(input("Choose number, type 99 to quit or 00 to see index: "))


    if tutorial_section == int(7):
        print()
        print()
        print()
        print()
        print("07 - INDEX")
        print()
        print("The index method is used for searching lists to find the index of the first occurance of a value.")
        print("knights = ['we', 'are', 'the', 'knights', 'who', 'say','ni']")
        print("print(knights.index('who'))")
        print("4")
        print()
        print("---- Program Section------")
        knights = ['we', 'are', 'the', 'knights', 'who', 'say', 'ni']
        knights.index('who')
        print(knights.index('who'))
        print()
        print("----Artificial print program----")
        print(" I couldn't type the next bit without this script breaking so I will show it in print format:")
        print(" print(knights.index('herring'))")
        print("Traceback (innermost last):")
        print("  File '<pyshell>', line 1 in ?")
        print("    knights.index('herring')")
        print("ValueError: list.index(x): x not in list")
        print("---end program---")
        print()
        print("When you search for the word 'who', you find that it's located at index 4:")
        print("print(knights[4])")
        print("who")
        print()
        print("----Program Section------")
        knights[4]
        print(knights[4])
        print("---end program---")
        print()
        print("However when you search for 'herring', you get an exception because the word is not found at all ")
        print()
        print("###-end of INDEX-###")
        
        tutorial_section = int(input("Choose number, type 99 to quit or 00 to see index: "))

    if tutorial_section == int(8):
        print()
        print()
        print()
        print()
        print("08 - INSERT")
        print()
        print("The insert method is used to insert an object into a list.")
        print()
        print("numbers = [1,2,3,4,5,6,7]")
        print("print(numbers)")
        print("[1,2,3, 'four',5,6,7]")
        print()
        print("----Program Section------")
        numbers = [1,2,3,4,5,6,7]
        numbers.insert(3, 'four')
        print(numbers)
        print("---end program---")
        print()
        print("     As with extend, you can implement insert with slice assignments")
        print()
        print("numbers = [1,2,3,4,5,6,7]")
        print("numbers[3:3] = ['four']")
        print("numbers")
        print()
        print("----Program Section------")
        numbers = [1,2,3,4,5,6,7]
        numbers[3:3] = ['four']
        print(numbers)
        print("---end program---")
        print()
        print("This may be fancy but it is hardly as readble as using insert")
        print()
        print("###-END OF INSERT-###")

        tutorial_section = int(input("Choose number, type 99 to quit or 00 to see index: "))
    
    if tutorial_section == int(9):
        print()
        print()
        print()
        print()
        print("09 - POP")
        print("The pop method removes an element (by default, the last one) from the list and returns it")
        print("x = [1,2,3]")
        print("print(x.pop())")
        print("3")
        print("print(x)")
        print([1,2])
        print("print(x.pop(0))")
        print("1")
        print("print(x)")
        print("2")
        print("----Program Section------")
        x = [1,2,3]
        print(x.pop())
        print(x)
        print(x.pop(0))
        print(x)
        print("---end program---")
        print()
        print("__________________________________________________________________________________________________________")
        print("     NOTE: The pop method is the only list method that both modifies the list and returns a value(other")
        print("     than None).")
        print("__________________________________________________________________________________________________________")
        print()
        print("Using pop, you can implement a common data structure called a stack. A stack like this works just like a stack of plates. You can put plates")
        print("on top, and you can remove plates from the top. The last one you put into the stack is the first one to be removed. (this principle is")
        print("called last-in, first-out, or LIFO)")
        print()
        print("The generally accepted names for the two stack operations(putting things in and taking them out) are push and pop.")
        print("Python doesn't have push but you can use append instead. The pop and append methods reverse eachothers results, so if you push")
        print("(or append) the value you just popped, you end up with the same stack")
        print()
        print("x = [1,2,3]")
        print("x.append(x.pop())")
        print("print(x)")
        print("[1,2,3]")
        print()
        print("----Program Section------")
        x = [1,2,3]
        x.append(x.pop())
        print(x)
        print("---end program---")
        print()
        print("____________________________________________________________________________________________________________")
        print("     TIP: if you want a first-in, first-out (FIFO) queue, you can use insert(o, ...) instead of Append.")
        print("Alternatively, you could keep using append but substitute pop(0) for pop(). An even better solution")
        print("would be to use a deque from the collections module.")
        print("____________________________________________________________________________________________________________")
        print()
        print("###-END OF POP-###")

        tutorial_section = int(input("Choose number, type 99 to quit or 00 to see index: "))



    if tutorial_section == int(99):
        break
print()
print()
print("I hope you enjoyed this little tutorial I wrote with the knowledge I learned while learning")
