import sys
import subprocess
print("\033[H\033[J", end="")
print()
print("Variables")
print("==========")
print("Variables are basically containers that store data that can be referenced at any time, they're very useful because of that feature")
print("To use a variable you must first type the name of the variable, in this example I am going to use 'name' once you've created the variable")
print("you must use the = operator to define it, you do it like this name = 'venatic' (ensure you use commas) now whenever you reference that")
print("variable later it will pass venatic to it. We can even use the print Function that you learned earlier to print the data of the varaible")
print("in plain text like this:")
print()
print('```Example')
print("name = 'venatic'")
print("print(name)")
print("```End Example")
print()
print("Below this line is going to be my itteration of the above code, you must use an IDE to view the source code:")
print()
print("---Program Start---")
name = 'venatic'
print(name)
print("---Program End---")
print()
print("If you're viewing from the terminal you won't be able to see the code behind it but it should just say 'venatic'")
print()
print()
print("Now you're probably wondering why we use commas, that is because there are 4 types of data that can be stored in a variable.")
print("The three different types of data that can be stored inside a variable are Strings, integers, floats and Boolean values.")
print("Strings are used if you want to use letters and they're defined with commas. Integers are numbers and so are floats but Python")
print("doesn't treat integers and floats the same way because a float uses decimal points. Boolean values are true or false statements")
print()
print("If you need to work with one specific type of data you can type cast them. To typecast simply use str(), int(), float() or bool().")
print("an example of where you would need to do this is when you're requesting one explicit type from the user or if you need")
print("to define a specific variable as an integer, float, string or bool. An example of a type cast looks like this:")
print()
print("age = int(20)")
print()
print("We can also now use the print Function to print the age which should be 20")
print()
print("print(age)")
print(20)
print()
print("Below this line is my itteration of the code, you need an IDE to see the source code or some kind of editor:")
print()
print("---Program Start---:")
age = int(20)
print(age)
print("---Program End---")
print()
print("Now if we try the same thing but set the variable to letssss say 20.1 and type cast it as an integer it will only print as 20")
print("because Python needs to be told how to handle a floating point number which is a number containing a decimal")
print()
print("age = int(20.1)")
print("print(age)")
print(20)
print()
print("To fix this you must first tell Python that the age variable is a float by type casting it like this:")
print()
print("age = float(20.1)")
print("print(age)")
print("20.1")
print()
print("Notice how Python now prints the proper decimal point? That's because we told it to.")
print("Below is my itteration of the code... Again use an IDE or editor to view the source code")
print()
print("---Program Start---")
age = int(20.1)
print(age)
print()
age = float(20.1)
print(age)
print("---Program End---")
print()
print()
print("Speaking of.... that reminds me that you can request input from the user which further allows more use of typecasting and some")
print("problems can also occur if you don't understand the difference between each type.")
print("To request input from the user you must use input('Question here: ') when assigning a variable(ensure to use, commas correctly.).")
print("An example of this is below:")
print()
print("Stored_Name = input('what is your Name?')")
print()
print("In the users terminal your python program will ask the user to input something, since it's not type casted they can put anything.")
print("however if you need the user to explicity use a number you could write it like this:")
print()
print("Stored_Age = int(input('what is your age?: ))")
print("The only downside is that if the user inputs anything but a number the program will show up with an error message because it expected")
print("an integer but likely got a string instead")






tutorial_complete = input("")